on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: 'test git actuins'
          run: pwd 

        - name: 'test printing'
          run: echo Maryam

        - name: 'print all contents'
          run: ls